.gitattributes
Example: https://github.com/DomKM/memefactory/blob/master/resources/public/contracts/src/Meme.sol
Solution sourced from: https://medium.com/@danielque/psa-how-to-fix-githubs-syntax-highlighting-for-solidity-4e9867c540b6
=> Make GitHub recognize .sol files as Solidity for syntax highlighting

README.md, project.clj, src/memefactory/ui/config.cljs, src/memefactory/ui/core.cljs, src/memefactory/ui/utils.clj
We needed this for the dank faucet, it requires the graphql endpoint
so we had to move the config out of core to avoid circular dependencies.
=> Moving the build environment to an env variable.

src/memefactory/server/core.cljs, src/memefactory/server/db.cljs, src/memefactory/server/dev.cljs, src/memefactory/server/graphql_resolvers.cljs, src/memefactory/server/syncer.cljs, src/memefactory/server/utils.cljs, src/memefactory/shared/graphql_schema.cljs
dd graphql mutation to blacklist a reg-entry image with reg-entry address and auth token as parameters
(token should be added in config, next to our private key, somewhere it doesn't end up on github)
When you blacklist a image it does two things :
- patches the image hash in meme table with a default image hash
- adds it to a blacklisted.edn file
Modify syncer so after replaying all past events, reads the blacklisted.edn and apply the patches again, then start.
=> Add blacklist implementation for images

src/memefactory/styles/component/buttons.clj, src/memefactory/ui/components/buttons.cljs
- 'Vote Reward' was changed to 'Claim <dank-logo> Reward'
- 'Challenge Reward' was changed to 'Claim <dank-logo> Reward'
- 'Reclaim Votes' was changed to 'Reclaim <dank-logo> Votes'
- fixes #194
=> Fixed 'Vote Reward' button labelling, along with several others

src/memefactory/server/graphql_resolvers.cljs, src/memefactory/ui/get_dank/events.cljs
The event handlers were broken for the DankFaucet, `on-success-n` is no longer available for `:http-xhrio` effects. Also after upgrading the Python Cryptography library it's now spitting warnings out to stderr. Since we have no good way to differentiate between warnings and errors I had to remove some (not all) of the error handling around calling the Python encryption script.
=> Fixed the event handlers and removed some python error handling.

src/memefactory/ui/get_dank/events.cljs
Minor fix for the Faucet front-end.
=> Pass the http-resp between events so we can extract the encrypted payload

src/memefactory/styles/component/compact_tile.clj
- fixes #301 
- added additional vendor prefixes for webkit for older browsers
- When viewing on a mobile, removed certain 3d animation effects (perspective, transform styling) which might be causing issues
=> Fixes for iphone animation performance issues

migrations/utils.js, src/memefactory/server/core.cljs, src/memefactory/server/dev.cljs, src/memefactory/shared/smart_contracts_dev.cljs, src/memefactory/shared/smart_contracts_prod.cljs, src/memefactory/shared/smart_contracts_qa.cljs, src/memefactory/shared/utils.clj, src/memefactory/ui/config.cljs, src/memefactory/ui/core.cljs, test/memefactory/tests/smart_contracts/deployment_tests.cljs, test/memefactory/tests/smart_contracts/utils.cljs, truffle.js
I propose following solution to the problem of configurable smart-contract addresses as a better alternative to async loading of contracts in UI. We can just have 3 smart_contracts.cljs files and based on MEMEFACTORY_ENV it'll choose the right one during the compilation.
=> Feature: Configurable smart-contracts based on ENV var

project.clj
Includes a version bump of district-ui-web3, with changes outlined in [this commit](https://github.com/district0x/district-ui-web3/commit/b59a07ad75c88f6035303c86c1301ac9333a11d8)
=> EIP1102 Fixes for deprecated authorization

src/memefactory/styles/component/account_balances.clj, src/memefactory/styles/component/app_bar.clj, src/memefactory/styles/pages/how_it_works.clj, src/memefactory/ui/components/account_balances.cljs, src/memefactory/ui/components/app_layout.cljs
- Fixes #438 
- Changes account balance width to be as wide as namebazaar, which shows appropriate margins for transaction logs
- Fixes #446 
- Removes media queries that are unintentionally removing coinbase logo
=> Transaction pop styling fix 438

project.clj
- Resulting code is unchanged, version number changed to a non-snapshot
=> Version Bump for district-ui-web3 to non-snapshot

src/memefactory/ui/core.cljs, src/memefactory/ui/my_settings/events.cljs, src/memefactory/ui/my_settings/page.cljs
Fix for #451, checks for the presence of an encrypted email in our mail contract and warns the user if they have an existing email address associated with a particular account. By moving the `subscribe` call for the active account to within the function body of the form-2 component it reacts well to changing accounts in Metamask.
Tested associating an email with an account, switching accounts, then associating an email with a different account.
=> Check the contract instead of local storage for the email

src/memefactory/ui/components/app_layout.cljs, src/memefactory/ui/meme_detail/page.cljs
Closes #525 .
Changes to meme-detail page and to app-layout to pass image as a custom tag.
Tested with a meta inspector, after it's on QA we can see if bots render the image.
=> fixes #525

src/memefactory/server/syncer.cljs
Closes #530 
Lazy call was never evaluated inside a Promise, this stopped tags from being persisted
Tags are now inserted into DB and should be displayed in UI.
=> non-lazy call

src/memefactory/ui/components/infinite_scroll.cljs, src/memefactory/ui/components/tiles.cljs
My proposed fix for #469. 
The flicker effect is caused by the fact that react-infinite component removes elements dynamically from the DOM, by default only 
This is controlled by the [preload-batch-size](https://github.com/seatgeek/react-infinite#number--object-preloadbatchsize) prop. I increased the preload to be of factor 6, so effectively only after scrolling for 6 x window size the elements get remounted.
=> increase the preload to avoid flicker

project.clj, src/memefactory/ui/core.cljs
This is a fix for #528. 
Bug is actually caused by the weird convention to use relative paths everywhere (first I saw it in index.html) and now in libraries  (**"./contracts/build/"**) but resurfaced after using the prerendering image to serve UI.
Contract artifacts were only loaded if navigating to the root route (**"/" => https://memefactory.qa.district0x.io/**), because then relative paths worked with static content, artifacts were empty if navigating directly to a nested path:
(**"dankregistry/submit" => https://memefactory.qa.district0x.io/dankregistry/submit**)
=> closes #528

project.clj, src/memefactory/styles/pages/dankregistry/submit.clj
Closes #483.
In the updated forms lib input is part of chips div, this make sit possible to use flex-wrap property and set it to always trail the remaining width.
=> dep+, css changes, closes #483

src/memefactory/server/db.cljs, src/memefactory/server/syncer.cljs
We should only assign numbers to whitelisted memes that doesn't have numbers. Also we should do it on memes reg entries since we are going to have param change reg entries.
=> Fix #521 (bug/Rejected memes show up as accepted in registry)

project.clj, src/memefactory/server/emailer.cljs
Fix for #596. 
Some email clients, most notably GMAIL have no support for svg and will explicitely block it. As a solution we will use a class to toggle their display in the emails.
=> closes #596

src/memefactory/server/db.cljs, src/memefactory/styles/component/buttons.clj
Tags should be normalized. This PR normalizes them at syncer level, where I think is the place to do it.
=> Normalize tags to lower-case when syncing meme events

project.clj, src/memefactory/server/contract/param_change.cljs, src/memefactory/server/core.cljs, src/memefactory/server/db.cljs, src/memefactory/server/dev.cljs, src/memefactory/server/syncer.cljs, src/memefactory/ui/config.cljs
This PR addresses a couple separate problems:
1. Infura drops idle ws connections after approximately 60 seconds, unfortunately quietly for the client, never triggering `on-disconnect`
2. Infura uses a cache of events, but presumably only for some of the web3 RPC calls. This manifested because when processing events we use `eth_getblockbynumber`  to get the event timestamp. 
This would throw a fatal exception (only when processing latest events), because even though they arrived the block was presumably not yet cached by infura.   
3. https://github.com/district0x/memefactory/issues/664
Ad 1) is addressed by altering the `server-web3-library` and adding a continuous keep-alive poll. Should it ever encounter an exception, the system goes into an offline mode and starts polling for the …
=> changes to keep the ws connection alive with a ping

src/memefactory/server/graphql_resolvers.cljs
No idea what is causing this and why it went unnoticed in QA, but for some reason using table alias instead of full name in this query doesn't work but doesn't throw either.
=> Fix #681 NSFW regression (2) change table alias to full name

src/memefactory/ui/meme_detail/page.cljs
The detail status header was broken for every meme. Looks like we broke it when we transitioned from calculate status in the server to calculate it on the client.
=> Fix #686 (Meme shows incorrect status)

src/memefactory/ui/components/app_layout.cljs
This PR implements changes requested in https://github.com/district0x/memefactory/issues/691 (update discord URL)
This PR only fixes the sidebar discord button. I'm not quite sure how to update this part:
https://github.com/district0x/memefactory/blob/92aaad0160bd3093a22cb20dcd319543ff61404a/resources/public/index.html#L71
=> update discord url in sidebar

project.clj, src/memefactory/styles/component/share_buttons.clj, src/memefactory/styles/core.clj, src/memefactory/ui/components/search.cljs, src/memefactory/ui/components/share_buttons.cljs, src/memefactory/ui/meme_detail/page.cljs
to fix https://github.com/district0x/memefactory/issues/701
Instagram doesn't provide sharing feature, so it's not possible to add a instagram button.
=> Add share buttons

project.clj, src/memefactory/ui/components/ens_resolver.cljs, src/memefactory/ui/core.cljs
Polygon RPCs seem to have some troubles with the way web3 v0.19 listens for specific contract events.
This causes the DANK balance not to be updated when spending or receiving DANK tokens as part of a transfer.
This PR is a workaround to fix that. It explicitly creates a watcher for checking the DANK account balance.
=> Fix account balances reloading

package.json, project.clj, src/memefactory/server/syncer.cljs
cljsjs/bignumber dependency is giving some troubles when compiling using optimizations (e.g., for qa/prod). This PR gets rid of it and rely on js/BigInt for parsing the token-id instead.
=> Replace bignumber dependency with native BigInt

project.clj, src/memefactory/ui/bridge/page.cljs, src/memefactory/ui/contract/bridge.cljs
Hide already exited transaction also for meme-token withdraw
bump version of district-server-web3 to fix exhausting connection when websocket reconnects.
=> Polygon migration

src/memefactory/ui/contract/bridge.cljs
in advanced compilation mode, the compiler shortens the names of properties and methods, to save space. Use a different way to call js matic method to avoid class renaming in there.
=> fix js call when using compiler optimization

migrations/13_memefactory_polygon_migration.js, package.json
The main migration file which deploys all memefactory contracts makes around 40 transactions. If only one of them fails, it will start over again. This PR modifies the migration file to retry from the latest successful transaction.
=> Make migrations resumable

src/memefactory/server/core.cljs, src/memefactory/server/syncer.cljs
When websocket connections restarts (e.g., if temporarily unavailable), the events were again gathered from the beginning. This PR keeps track of the block number so it resumes the event gathering from the last gather block (minus a short amount) instead.
=> Continue syncing from last block after web3 reconnects

src/memefactory/server/core.cljs, src/memefactory/server/graphql_resolvers.cljs, src/memefactory/server/syncer.cljs
Force reset websocket connection to provider to avoid miss events when long connected.
Connection is periodically closed (2 hours by default), so next time it pings it will automatically reconnect again
Also modify sql query to show all resolved param changes
=> Reset wss periodically and show all resolved params
