district0x/memefactory

- resources/public/contracts/src/RegistryEntry.sol
- src/memefactory/server/contract/registry_entry.cljs
- src/memefactory/server/generator.cljs
- src/memefactory/server/syncer.cljs
- src/memefactory/shared/contract/registry_entry.cljs
Splitted the function and refactored every place that was calling loadRegistryEntry.
> Move apart RegistryEntry.sol loadRegistryEntry challenge info into loadRegistryEntryChallenge.

- src/memefactory/server/db.cljs
From user-exsits? to user-exists?
> Fix small typos

- project.clj
- src/memefactory/server/graphql_resolvers.cljs
**IMPORTANT** 
https://github.com/district0x/district-server-db/pull/1 should be merged and released before
> Replacing uneeded sql/raw calls with its honeysql syntax

- README.md
- src/memefactory/shared/graphql_schema.cljs
- src/memefactory/shared/routes.cljs
- src/memefactory/ui/core.cljs
- src/memefactory/ui/leaderboard/page.cljs
- test/memefactory/tests/graphql_resolvers/graphql_resolvers_tests.cljs
What is done:
- route for `/leaderboard/curators`
- page `/leaderboard/curators`
- `(testing "Test order-by curator-total-earned" ...`
- values for curators
- infinite scroll
Additionally:
- fix typo in `graphql_schema.cljs`
- add to readme info about `ipfs daemon` for development
What is not done:
- no CSS styles
> curators page

- project.clj
EIP-1102 Fix - district-ui-web3 Version Bump from 1.0.1 to 1.1.0-SNAPSHOT
> EIP-1102 Fix

- project.clj
- src/memefactory/styles/pages/memefolio/details.clj
- src/memefactory/styles/pages/mymemefolio.clj
- src/memefactory/ui/core.cljs
- src/memefactory/ui/meme_detail/page.cljs
- src/memefactory/ui/memefolio/page.cljs
styling ttries to followi maintainable css conventions
> spinners styling

- contracts/RegistryEntry.sol
- src/memefactory/server/contract/registry_entry.cljs
- src/memefactory/server/dev.cljs
- src/memefactory/server/emailer.cljs
- src/memefactory/server/emailer/templates.cljs
- src/memefactory/server/generator.cljs
* read only solidity reg-entry status function
* generator changes (claiming challenge reward)
* fixed emailer crashes + added logging
* small changes to email templates (use titles not contract addresses)
> fixed emailer crash

- project.clj
- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/components/tiles.cljs
- Fixes to flippable tile to transition without glitches
- Additional fixes to elements contained within the flippable tiles to adhere to the new implementation
- vbumped figwheel version to match figwheel-sidecar version
- fixes #170 
- fixes #111
> Fixes to flippable tile, glitchyness fixes, animation improvements

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/components/tiles.cljs
- fixed transitions to not be in effect when the card is on the back-side
- more layout fixes for flippable cards when creating offerings
- fixes issue #154
> Added 'View Details' button to meme cards (auction and meme) w- more fixes

- src/memefactory/ui/components/buttons.cljs
> Bug fix for reclaim votes for non-challenger

- src/memefactory/styles/component/compact_tile.clj
> Fixes tile background gradient styling

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/components/challenge_list.cljs
- src/memefactory/ui/components/tiles.cljs
- src/memefactory/ui/meme_detail/page.cljs
- src/memefactory/ui/memefolio/page.cljs
- banner was added to challenge list, meme details and memefolio (created)
- fixes #205
> REJECTED banner added to rejected memes

- src/memefactory/styles/component/buttons.clj
- src/memefactory/styles/pages/memefolio/details.clj
- src/memefactory/ui/dank_registry/challenge_page.cljs
- src/memefactory/ui/dank_registry/submit_page.cljs
- src/memefactory/ui/dank_registry/vote_page.cljs
- src/memefactory/ui/meme_detail/page.cljs
Fixes for several things
- Fixes for #218, made challenge card pink for homepage
- Fixes for #219, Add DANK logo to 'Get Dank' header button
- Fixes for #225, fixed meme details icon cutoff
- Minor formatting fixes of parenthesis (editor did it automatically, won't affect styling)
> Multi fix #225 #219 #218

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/memefolio/page.cljs
- changed positioning a bit as suggested
- added correct gql rulings to get the status for curated pages
- added hover animation to reveal original meme without the 'stank' badge
- fixes #242
> Fixed 'Stank' tags, added hover animation

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/styles/container/tiles.clj
- also added better animation timings, fixed overflow to prevent clipping
> Better implementation of flippable tiles with 3d perspective

- src/memefactory/styles/pages/dankregistry/submit.clj
- src/memefactory/ui/components/general.cljs
- fixes issue #286
- fixes issue #285
> Fixes to submission button styling

- src/memefactory/styles/component/challenge_list.clj
- src/memefactory/styles/component/form.clj
- src/memefactory/styles/component/search.clj
- src/memefactory/styles/pages/dankregistry/vote.clj
- fixes to vote -> open challenges sort select
- fixes to vote -> resolved challenges sort select
- fixes to challenges -> sort select
- fixes to dank registry search sort select
- fixes #284
> input select box fixes to fit content

- src/memefactory/styles/component/app_bar.clj
- src/memefactory/ui/components/app_layout.cljs
- fixes #281 
- reintroduces some things that were commented out, might require some more tweaking
> Fixed transaction log bar

- src/memefactory/styles/component/app_bar.clj
- src/memefactory/styles/pages/dankregistry/submit.clj
- src/memefactory/ui/components/app_layout.cljs
- more fixes for #281
- more styling fixes for submit button, issue #286
> More top-right account balance styling fixes

- src/memefactory/ui/components/challenge_list.cljs
> Fix creator/challenge rank to show N/A for missing cases

- src/memefactory/ui/components/tiles.cljs
> Disabled buy buttons when there are no active accounts

- src/memefactory/styles/base/colors.clj
- src/memefactory/styles/pages/mymemefolio.clj
> Fixes cancel button styling for offerings

- src/memefactory/ui/memefolio/page.cljs
> Fixed back of memefolio -> selling tab to show description text

- src/memefactory/styles/component/buttons.clj
- src/memefactory/styles/component/form.clj
- src/memefactory/styles/pages/dankregistry/challenge.clj
- src/memefactory/styles/pages/dankregistry/vote.clj
- src/memefactory/styles/pages/memefolio/details.clj
- src/memefactory/ui/dank_registry/challenge_page.cljs
- src/memefactory/ui/dank_registry/submit_page.cljs
- src/memefactory/ui/dank_registry/vote_page.cljs
- src/memefactory/ui/meme_detail/page.cljs
- Fixes Issue #313
- for submit, vote and challenge pages
- Fixes Issue #314
- Fixes Issue #315
> Fixes to non-active accounts and disabled buttons

- project.clj
- src/memefactory/styles/app_layout.clj
- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/styles/pages/home.clj
- src/memefactory/ui/components/app_layout.cljs
- src/memefactory/ui/components/tiles.cljs
- src/memefactory/ui/core.cljs
- src/memefactory/ui/mobile.cljs
- src/memefactory/ui/subs.cljs
- Added district.ui.mobile repository to memefactory
- Flippable Tile animations will now downgrade when it detects that it's being viewed on a mobile device
- Coinbase message will now appear if a mobile-compatible device without an active account views the site
- Fixes issue #339
- Fixes issue #336
> Mobile Features and Fixes

- src/memefactory/ui/components/tiles.cljs
- src/memefactory/ui/memefolio/page.cljs
> Fixed flip animations for memefolio flippable tiles

- src/memefactory/styles/pages/get_dank.clj
> Fixed styling on 'Get Dank' page for mobile and tablet devices

- src/memefactory/styles/component/account_balances.clj
> Fixes to account balances tx section to fit the width

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/home/page.cljs
- Fixes issue #351
- Challenge message was added to the description section as well
> Fix trending votes to match the other tiles styling

- src/memefactory/styles/component/account_balances.clj
> styling fix for account balance bug

- project.clj
- src/memefactory/server/dev.cljs
- src/memefactory/server/emailer.cljs
- src/memefactory/server/emailer/templates.cljs
- Fixes Issue #233
- Added the argument `--nostart` to dev.cljs to prevent mounting while in development mode
- This was so I didn't have to deal with mounting everything, while working on the emailer. Let me know if you want me to remove it.
- Added hiccups library
- Used with the templates
- Split up emailer functions for easier testing
- These are tied into the original emailer. (This isn't fully tested, need some help with this @fbielejec @jpmonettas)
- Template on SendGrid was rewritten, going to need some guidance on any additional changes.
- The changes fixed several issues, I haven't noticed any new issues.
- Template is now a bit more responsive, should work on mobiles >480px in width.
- DANK amounts supplied are now rounded to the 3rd decimal place
- My testing required that I …
> Fixes to Email Templates

- docker-builds/server/Dockerfile
- docker-builds/ui/Dockerfile
- docker-builds/ui/memefactory.io
- docker-builds/ui/nginx.conf
- docker-push.sh
- src/memefactory/server/core.cljs
> gzipped content, minimized container images

- src/memefactory/server/emailer.cljs
> Fix root-url links which include extra slash

- migrations/2_memefactory_migration.js
- truffle.js
Set the params for production.
> Change dank faucet params

- src/memefactory/ui/memefolio/page.cljs
This should also fix issues/457
> Fix #464 (Add issue/auction form limits based on gas costs)

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/components/tiles.cljs
- This also fixes issues with browse page fading in elements, since all fading animations were removed
> Fixes Issue #469

- src/memefactory/styles/component/compact_tile.clj
- src/memefactory/ui/components/tiles.cljs
- This puts back in the fade effects, The fix unintentionally broke the flip animations on some platforms
> Revert broken fix for issue #469

- src/memefactory/ui/core.cljs
- src/memefactory/ui/my_settings/events.cljs
Explicit event flow for loading user (encyrpted) email address + more logging around the associated events
> explicit event flow

- src/memefactory/server/graphql_resolvers.cljs
- src/memefactory/server/syncer.cljs
> WIP : speeding up syncing

- workflow.md
In the past we have had very little planning and testing, which has resulted in some duplicated or not-needed work and many regressions / downtime.
In order to maximize the output from a small team such as ours, we need some planning going forward.
This proposal lays out a proposal of a possible workflow, it is loosely inspired by the agile approach.
Whole team is invited to participate in the discussion, you can leave your comments as PRs.
> WIP : proposed workflow and planning document

- qa-test-stories.md
Adding document that should be followed by ops (and dev) guys when checking QA, before updates can be pushed into production.
> add QA test stories document

- project.clj
- src/memefactory/styles/component/form.clj
- src/memefactory/styles/pages/dankregistry/submit.clj
Updates to the forms library requires some changes to the css.
No visible changes, just fixing html to avoid using non `:li` elements in a list
> css changes to accomodate updated forms lib

- src/memefactory/styles/pages/memefolio/details.clj
- src/memefactory/ui/meme_detail/page.cljs
Detail-page now recognizes if a meme has no reg-entry/address and displays information accordingly.
Changes to html, css and a few formatting changes.
> closes #423

- src/memefactory/styles/component/form.clj
- src/memefactory/styles/component/search.clj
- src/memefactory/styles/pages/dankregistry/submit.clj
CSS across all pages that use chips input and its form.
> closes #483

- project.clj
Dependency update, closes #553
> closes #553

- src/memefactory/ui/components/tiles.cljs
Addresses #575 (video memes flipping)
> closes #575

- src/memefactory/ui/about/page.cljs
- src/memefactory/ui/components/app_layout.cljs
- src/memefactory/ui/get_dank/page.cljs
- src/memefactory/ui/how/page.cljs
- src/memefactory/ui/privacy_policy/page.cljs
- src/memefactory/ui/terms/page.cljs
Mitigation for [tab-nabbing attacks](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/).
Very small probaility as the malicious code would have to be coming from us, but with an easy fix I decided to go for it.
> mitigate tab nabbing

- src/memefactory/ui/dank_registry/vote_page.cljs
Fix for #580 (blurred text on button labels).
> closes #580

- src/memefactory/ui/about/page.cljs
- src/memefactory/ui/components/app_layout.cljs
- src/memefactory/ui/get_dank/page.cljs
- src/memefactory/ui/how/page.cljs
- src/memefactory/ui/privacy_policy/page.cljs
- src/memefactory/ui/terms/page.cljs
> fix broken html

- src/memefactory/ui/param_change/page.cljs
Replaces lorem ipsums in parm pages + change params display order
> Fix #600 (Parameter Page Copy)

- src/memefactory/ui/get_dank/events.cljs
removing leftover debug statement.
> remove debugging

- contracts/DankFaucet.sol
- migrations/8_redeploy_faucet_migration.js
- src/memefactory/shared/smart_contracts_qa.cljs
big lol. conditions in require need to be reversed OC :/
> omg forgot to reverse the conditions

- contracts/Registry.sol
- contracts/RegistryEntry.sol
- contracts/registryentry/RegistryEntryLib.sol
- migrations/10_remove_vote_quorum_migration.js
- migrations/2_memefactory_migration.js
- src/memefactory/server/graphql_resolvers.cljs
- src/memefactory/shared/contract/registry_entry.cljs
- src/memefactory/shared/utils.cljs
- src/memefactory/ui/config.cljs
- src/memefactory/ui/param_change/page.cljs
- test/memefactory/tests/smart_contracts/registry_entry_tests.cljs
- truffle.js
The migration was tested by : 
- with current master deploying from scratch and submitting memes and param changes
- running migration 10
- verifying meme and param change submission still works
> Fix #636 Remove vote quorum parameter

- .circleci/config.yml
- README.md
- docker-push.sh
- migrations/10_remove_vote_quorum_migration.js
- migrations/4_dev_migration.js
- migrations/5_dev_migration.js
- migrations/6_db_keys_fix_migration.js
- migrations/7_param_changes_migration.js
- migrations/8_redeploy_faucet_migration.js
- migrations/9_fix_param_deposit.js
- migrations/check_ran_migrations.js
- package-lock.json
- project.clj
- src/memefactory/shared/smart_contracts_prod.cljs
- test/memefactory/tests/runner.cljs
- test/memefactory/tests/smart_contracts/meme_auction_tests.cljs
- test/memefactory/tests/smart_contracts/meme_tests.cljs
- test/memefactory/tests/smart_contracts/param_change_tests.cljs
- test/memefactory/tests/smart_contracts/registry_entry_tests.cljs
- test/memefactory/tests/smart_contracts/registry_tests.cljs
- test/memefactory/tests/smart_contracts/utils.cljs
- truffle.js
[comment]: # (Summarise the problem and how the pull request solves it. You can use github links)
...
Documentation changes
> WIP: CircleCI migration + check ran migrations script

- src/memefactory/shared/smart_contracts_prod.cljs
prod addresses after migration 10
> mainnet migration 10

- src/memefactory/server/syncer.cljs
web3 returns mixed-cased addresses, confusing our resolvers. This hopefully fixes all of that by lower-casing all known address arguments directly when processing events in the syncer.
> lowercasing all known addresses

- project.clj
- src/memefactory/server/core.cljs
- src/memefactory/server/dev.cljs
- src/memefactory/server/syncer.cljs
Upgrade to a web3 version with ping function. Start pinging after resync completes.
> start pinging after resync

- src/memefactory/ui/components/challenge_list.cljs
Since challenge-list is also used from resolved challenges tab it's query
should contain :challenge/votes-for and :challenge/votes-against
> Challenge list query should contain votes.

- src/memefactory/server/graphql_resolvers.cljs
from what I can see it is a regression and has been broken for 3 months now,
the fix was introduced november 13 in https://github.com/district0x/memefactory/commit/8d5c5617c9fe2f818cd88f4ec14e3904fdce54ae
and the web3 migration merge on november 25 broke it https://github.com/district0x/memefactory/commit/d8171a38a5223c0d5df7d37e9cb9d002e1749087
> Fix #681 NSFW regression

- contracts/DankFaucet.sol
- migrations/11_set_faucet_gas_price_migration.js
- src/memefactory/shared/smart_contracts_qa.cljs
- truffle.js
We expose the oraclize(provable) gasPrice parameter allowing to set the callback gas price as prices on the network evolve.
> update Faucet contract, allow setting _callback txs gas price

- .dockerignore
- docker-builds/server/Dockerfile
- docker-builds/ui/Dockerfile
- docker-push.sh
This PR updates Dockerfiles to process all the build steps inside multistage docker build
> DRAFT :Update dockerfiles

- project.clj
- src/memefactory/shared/smart_contracts_qa.cljs
Set QA contracts for goerli/mumbai
> Set QA contracts for goerli/mumbai

- project.clj
- src/memefactory/shared/smart_contracts_qa.cljs
> Set QA contracts for goerli/mumbai (v2)

- package.json
Add bignumber.js node dependency
> Added missing node dependency

- src/memefactory/ui/config.cljs
> Fix hostname prefix

- project.clj
- src/memefactory/server/core.cljs
- src/memefactory/server/dank_faucet_twitter.cljs
- src/memefactory/styles/app_layout.clj
- src/memefactory/styles/component/main_content.clj
- src/memefactory/ui/components/app_layout.cljs
Use new version of district-server-web3-events to enable checkpoints for faster boot
Enable get DANK button in menu bar
> web3-events lib update and show DANK menu button

- src/memefactory/ui/config.cljs
Change Polygon RPC urls to use the default one
> Change Polygon RPC urls

- src/memefactory/styles/pages/get_dank.clj
- src/memefactory/ui/dank_registry/vote_page.cljs
- src/memefactory/ui/get_dank/events.cljs
- src/memefactory/ui/get_dank/page.cljs
- src/memefactory/ui/how/page.cljs
Added button to import DANK token to wallet.
Also adjusted some texts
> Add button to import DANK to wallet

- src/memefactory/server/core.cljs
- src/memefactory/server/twitter_bot.cljs
- src/memefactory/ui/config.cljs
- Replace "memefactory.io" references to "v1.mememfactory.io"
- Replace "api.memefactory.io" to "apiv1.memefactory.io"
> Change v1 graphql endpoint url

- src/memefactory/server/dank_faucet_twitter.cljs
> Show error if relayer fails

- src/memefactory/server/dank_faucet_twitter.cljs
- src/memefactory/server/syncer.cljs
- src/memefactory/server/twitter_bot.cljs
- src/memefactory/server/utils.cljs
- src/memefactory/styles/pages/param_changes.clj
- src/memefactory/ui/param_change/page.cljs
fix for 
- https://github.com/district0x/memefactory/issues/756
- https://github.com/district0x/memefactory/issues/755
> Fix twitter bot and collapse parameter table

- src/memefactory/server/dank_faucet_twitter.cljs
- src/memefactory/server/db.cljs
- src/memefactory/server/twitter_bot.cljs
Use extended mode in faucet to allow getting tweet full text
Add twitter notifications when submitting or challenging a parameter change
some fixes
> Faucet and Twitter bot improvements

- src/memefactory/server/dank_faucet_twitter.cljs
Automatic oauth re-authentication does not seem to work on defender-relay-client. To solve this, we instance a new Relayer object for each request.
This should fix https://github.com/district0x/memefactory/issues/764
> Fix relayer unathorized on faucet

- migrations/26_set_faucet_amount.js
> Set DANK amount in faucet

- package.json
- src/memefactory/server/core.cljs
- src/memefactory/server/dank_faucet_discord_bot.cljs
Added Discord bot for invoking faucet from a discord channel
> Implement Faucet Discord bot

- src/memefactory/server/twitter_bot.cljs
- src/memefactory/styles/component/discord.clj
- src/memefactory/styles/pages/get_dank.clj
- src/memefactory/ui/get_dank/page.cljs
Change UI to use DANK Faucet from discord
Small fix for Twitter bot
>  Change UI to use DANK Faucet from discord

- src/memefactory/styles/pages/dankregistry/submit.clj
- src/memefactory/ui/contract/meme_factory.cljs
- src/memefactory/ui/dank_registry/events.cljs
- src/memefactory/ui/dank_registry/submit_page.cljs
In submit form, show uploaded image cropped to try to avoid poor quality submissions due to wrong ratio.
Also, fix for https://github.com/district0x/memefactory/issues/771
> Submit form enhancements
